version: '3.4'

services:
 FAPsql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"   # Manjunath : earlier port 5433     # Important: In a production environment your should remove the external port - 

 FAPidentity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_AZURE_IDENTITY_DB:-Server=172.19.0.2,1433;Database=FoodApp.Services.IdentityDb;User Id=sa;Password=Pass@word}
      - ConnectionString_IdentityConfigStore=${ESHOP_AZURE_IDENTITY_CONFIG_DB:-Server=172.19.0.2,1433;Database=FoodApp.Services.IdentityConfigDb;User Id=sa;Password=Pass@word}
      - UseCustomizationData=True  
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "6105:80"   # Manjunath : earlier port 5105