version: '3.4'

services:
  FAPidentity.api:
    image: manvekar/identity.api:dev
    build:
      target: base
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_FAPidentity.api$
    volumes:
      - C:\MYP\MAPP\FoodSurveyApp\src\Services\Identity\Identity.API:/app
      - C:\Users\Manjunath_Anvekar\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_FAPidentity.api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_FAPidentity.api$ bin/Debug/netcoreapp2.2/Identity.API.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
